export type PlanId = "starter" | "professional" | "enterprise";

export const PRICING_PLANS = [
  {
    id:          "starter",
    name:        "Starter",
    badge:       null,
    highlighted: false,
    description: "Perfect for small teams getting compliant.",
    cta:         "Start Free Trial",
    price:       { KES: 15_000, AED: 500,   USD: 120 },
    priceAnnual: { KES: 12_000, AED: 400,   USD: 96  },
    features: [
      { label: "Users",                          included: true,  limit: "5"        },
      { label: "Document storage",               included: true,  limit: "200 docs" },
      { label: "Compliance tracker",             included: true                     },
      { label: "Incident reporting",             included: true                     },
      { label: "Basic reporting",                included: true                     },
      { label: "Audit management",               included: false                    },
      { label: "Training matrix",                included: false                    },
      { label: "Virtual consultant access",      included: false                    },
      { label: "Custom regulation library",      included: false                    },
      { label: "Priority support",               included: false                    },
    ],
  },
  {
    id:          "professional",
    name:        "Professional",
    badge:       "Most Popular",
    highlighted: true,
    description: "For growing companies with active HSEQ programs.",
    cta:         "Start Free Trial",
    price:       { KES: 35_000, AED: 1_200, USD: 280 },
    priceAnnual: { KES: 28_000, AED: 960,   USD: 224 },
    features: [
      { label: "Users",                           included: true,  limit: "25"         },
      { label: "Document storage",                included: true,  limit: "2,000 docs" },
      { label: "Compliance tracker",              included: true                       },
      { label: "Incident reporting",              included: true                       },
      { label: "Advanced reporting & analytics",  included: true                       },
      { label: "Full audit management",           included: true                       },
      { label: "Training matrix",                 included: true                       },
      { label: "Virtual consultant",              included: true,  limit: "2 hrs/mo"   },
      { label: "Custom regulation library",       included: false                      },
      { label: "Priority support",                included: false                      },
    ],
  },
  {
    id:          "enterprise",
    name:        "Enterprise",
    badge:       "Full-Service",
    highlighted: false,
    description: "Unlimited scale with dedicated expert support.",
    cta:         "Contact Sales",
    price:       { KES: 80_000, AED: 2_800, USD: 640 },
    priceAnnual: { KES: 64_000, AED: 2_240, USD: 512 },
    features: [
      { label: "Users",                           included: true,  limit: "Unlimited" },
      { label: "Document storage",                included: true,  limit: "Unlimited" },
      { label: "Compliance tracker",              included: true                      },
      { label: "Incident reporting",              included: true                      },
      { label: "Advanced reporting & analytics",  included: true                      },
      { label: "Full audit management",           included: true                      },
      { label: "Training matrix",                 included: true                      },
      { label: "Dedicated virtual consultant",    included: true                      },
      { label: "Custom regulation library",       included: true                      },
      { label: "Priority 24/7 support",           included: true                      },
    ],
  },
] as const;

export type Plan = (typeof PRICING_PLANS)[number];
